import 'package:cloud_firestore/cloud_firestore.dart';

import 'item.dart';
import 'item_category.dart';

class Pantry {
  Pantry(
      {required this.title,
        List<ItemCategory>? categories,}) : categories = categories ?? [];

      //TODO required String pantryId;
      //TODO required String(userId) founder
      //TODO optional SvgPicture backgroundImage = default_image_asset
      //TODO List<String(userId), Item> activityHistory = []

  List<ItemCategory> categories = [];

  //Change later to add user as stated in to do above
  List<Item> activityHistory = [];

  String? _pantryID;
  String? get pantryID => _pantryID;
  void setPantryID (DocumentReference documentReference) async {
    _pantryID = documentReference.id;
    //TODO: Add ID, generated by firebase from collection pantries[document ID]. This should happen when the user has finished clicking through the add pantry process.
  }


  bool _selectedForShopping = true;
  bool get selectedForShopping => _selectedForShopping;
  void toggleSelectedForShopping(bool newValue) {
    _selectedForShopping = newValue;
  }

  String title;
  void editTitle(String newTitle) {
    title = newTitle;
  }

  bool _selectedForPushNotifications = true;
  bool get selectedForPushNotifications => _selectedForPushNotifications;
  void toggleSelectedForPushNotifications(bool newValue) {
    _selectedForPushNotifications = newValue;
  }
}