// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBzqHVOLdcUWNjZrLhfNSuC-MONG4v1M',
    appId: '1:248552006510:web:0be6035207e4be5b57577f',
    messagingSenderId: '248552006510',
    projectId: 'shared-pantry',
    authDomain: 'shared-pantry.firebaseapp.com',
    storageBucket: 'shared-pantry.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeA_aQFXMzORQ0xKtizh1j0ZwbTNoHzQ',
    appId: '1:248552006510:android:1760ba24a98fd65157577f',
    messagingSenderId: '248552006510',
    projectId: 'shared-pantry',
    storageBucket: 'shared-pantry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNJywZ06vkZp9VG99DE6hBX02XLNpuohA',
    appId: '1:248552006510:ios:83ff5cca2833667c57577f',
    messagingSenderId: '248552006510',
    projectId: 'shared-pantry',
    storageBucket: 'shared-pantry.appspot.com',
    iosClientId: '248552006510-4eg9bok7l1mddm3cvgtpbgf97lb9nag4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedPantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNJywZ06vkZp9VG99DE6hBX02XLNpuohA',
    appId: '1:248552006510:ios:83ff5cca2833667c57577f',
    messagingSenderId: '248552006510',
    projectId: 'shared-pantry',
    storageBucket: 'shared-pantry.appspot.com',
    iosClientId: '248552006510-4eg9bok7l1mddm3cvgtpbgf97lb9nag4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedPantry',
  );
}
